<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ModelSync.Exploration</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ModelSync.Core\ModelSync.Core.csproj" />
  </ItemGroup>
</Project>
