namespace ModelSync.Core;

/// <summary>
/// The catalog of incremental change operations (CMD operations).
/// Create/Delete target elements; Modify specializes into Set/Unset (single),
/// Add/Remove (set), Put/Remove (map) and Insert/Remove (list).
/// </summary>
public enum OperationType
{
    /// <summary>Sentinel used for the operation-tree root only.</summary>
    Root = 0,

    CreateElement,
    DeleteElement,

    SetProperty,
    UnsetProperty,

    AddSetItem,
    RemoveSetItem,

    PutMapEntry,
    RemoveMapEntry,

    /// <summary>Insert a list item with a stable item id after an anchor item (null anchor = head).</summary>
    InsertListItem,
    RemoveListItem
}

/// <summary>
/// A discrete, atomic change applied to a model. Operations are immutable,
/// globally identified, and are the only way a workspace evolves.
/// Replaying the operation path from the tree root reproduces the model state.
/// </summary>
public sealed record Operation
{
    public required Guid Id { get; init; }
    public required OperationType Type { get; init; }

    /// <summary>Workspace that authored the operation.</summary>
    public string WorkspaceId { get; init; } = string.Empty;

    public string ElementId { get; init; } = string.Empty;

    /// <summary>Optional reference to the element acting as this element's type (streamlined MOF).</summary>
    public string? ElementTypeId { get; init; }

    public string? PropertyName { get; init; }
    public PropertyValue? Value { get; init; }

    /// <summary>Stable identity of a list item (list operations only).</summary>
    public string? ItemId { get; init; }

    /// <summary>Anchor item the insert goes after; null inserts at the head (list inserts only).</summary>
    public string? AfterItemId { get; init; }

    public string? MapKey { get; init; }

    /// <summary>True when the operation was generated by conflict resolution rather than a user.</summary>
    public bool IsResolution { get; init; }

    public DateTimeOffset Timestamp { get; init; } = DateTimeOffset.UtcNow;

    public bool IsElementOperation => Type is OperationType.CreateElement or OperationType.DeleteElement;

    public bool IsPropertyOperation => Type is
        OperationType.SetProperty or OperationType.UnsetProperty or
        OperationType.AddSetItem or OperationType.RemoveSetItem or
        OperationType.PutMapEntry or OperationType.RemoveMapEntry or
        OperationType.InsertListItem or OperationType.RemoveListItem;

    /// <summary>
    /// True for operations that add or change content, false for removals.
    /// Element deletes vs. "destructive" property operations are pseudo conflicts,
    /// vs. "constructive" ones real conflicts.
    /// </summary>
    public bool IsConstructive => Type is
        OperationType.CreateElement or OperationType.SetProperty or
        OperationType.AddSetItem or OperationType.PutMapEntry or
        OperationType.InsertListItem;

    public Operation CloneAsResolution(string workspaceId) => this with
    {
        Id = Guid.NewGuid(),
        WorkspaceId = workspaceId,
        IsResolution = true,
        Timestamp = DateTimeOffset.UtcNow
    };

    public override string ToString() => Type switch
    {
        OperationType.Root => "Root",
        OperationType.CreateElement => $"Create {ElementId}{(ElementTypeId is null ? "" : $" : {ElementTypeId}")}",
        OperationType.DeleteElement => $"Delete {ElementId}",
        OperationType.SetProperty => $"Set {ElementId}.{PropertyName} = {Value}",
        OperationType.UnsetProperty => $"Unset {ElementId}.{PropertyName}",
        OperationType.AddSetItem => $"Add {ElementId}.{PropertyName} += {Value}",
        OperationType.RemoveSetItem => $"Remove {ElementId}.{PropertyName} -= {Value}",
        OperationType.PutMapEntry => $"Put {ElementId}.{PropertyName}[{MapKey}] = {Value}",
        OperationType.RemoveMapEntry => $"Remove {ElementId}.{PropertyName}[{MapKey}]",
        OperationType.InsertListItem => $"Insert {ElementId}.{PropertyName} item {ItemId} = {Value} after {AfterItemId ?? "<head>"}",
        OperationType.RemoveListItem => $"Remove {ElementId}.{PropertyName} item {ItemId}",
        _ => base.ToString() ?? string.Empty
    };
}
